'use client'
import { createContext, useContext, useState } from 'react'

const LangContext = createContext({})

export const translations = {
  en: {
    appName: 'Public Sheba DHK',
    liveMap: 'Live Map',
    reportIssue: 'Report Issue',
    admin: 'Admin',
    signIn: 'Sign in',
    signOut: 'Sign out',
    outages: 'Outages',
    issues: 'Issues',
    normal: 'Normal',
    liveReports: 'Live reports',
    total: 'total',
    noReports: 'No reports yet.',
    havingIssue: 'Having a utility issue?',
    reportIn20: 'Report it in 20 seconds — help your neighbours know',
    reportNow: 'Report now',
    loadingMap: 'Loading live data...',
    reportTitle: 'Report a utility issue',
    reportSubtitle: 'Takes less than 30 seconds',
    yourArea: 'Your area',
    selectZone: 'Select your zone...',
    issueType: 'Issue type',
    utilityType: 'Utility type',
    howLong: 'How long has this been happening?',
    extraDetails: 'Extra details',
    optional: 'optional',
    detailsPlaceholder: 'e.g. no water since morning, no notice from WASA...',
    submitReport: 'Submit report',
    submitting: 'Submitting...',
    reportSuccess: 'Report submitted!',
    reportSuccessMsg: 'Thank you. Your report helps your neighbours. Redirecting to map...',
    signInRequired: 'Sign in required',
    signInRequiredMsg: 'You need to be signed in to submit a report.',
    signInNow: 'Sign in now',
    fillAllFields: 'Please fill in all required fields.',
    signInToReport: 'Please sign in to submit a report.',
    noWater: 'No water supply',
    lowPressure: 'Low pressure',
    discoloured: 'Discoloured water',
    badSmell: 'Bad smell',
    noPower: 'No electricity',
    lowVoltage: 'Low voltage',
    frequentCuts: 'Frequent load shedding',
    noGas: 'No gas supply',
    lowGasPressure: 'Low gas pressure',
    under1hr: 'Less than 1 hour',
    oneToThreeHrs: '1 to 3 hours',
    over3hrs: 'More than 3 hours',
    meToo: 'Me too',
    signInToConfirm: 'Please sign in to confirm a report.',
    normalSupply: 'Normal supply',
    someIssues: 'Some issues reported',
    outageConfirmed: 'Outage confirmed',
    reportsIn2hrs: 'reports in last 2 hrs',
    water: 'Water',
    electricity: 'Electricity',
    gas: 'Gas',
    allUtilities: 'All utilities',
    stats: 'Stats',
    history: 'Zone History',
  },
  bn: {
    appName: 'পাবলিক সেবা ঢাকা',
    liveMap: 'লাইভ ম্যাপ',
    reportIssue: 'সমস্যা জানান',
    admin: 'অ্যাডমিন',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    outages: 'বিভ্রাট',
    issues: 'সমস্যা',
    normal: 'স্বাভাবিক',
    liveReports: 'লাইভ রিপোর্ট',
    total: 'মোট',
    noReports: 'এখনো কোনো রিপোর্ট নেই।',
    havingIssue: 'সেবা সমস্যা হচ্ছে?',
    reportIn20: '২০ সেকেন্ডে জানান — প্রতিবেশীদের সাহায্য করুন',
    reportNow: 'এখনই জানান',
    loadingMap: 'লাইভ তথ্য লোড হচ্ছে...',
    reportTitle: 'সমস্যা জানান',
    reportSubtitle: '৩০ সেকেন্ডেরও কম সময় লাগবে',
    yourArea: 'আপনার এলাকা',
    selectZone: 'আপনার জোন বেছে নিন...',
    issueType: 'সমস্যার ধরন',
    utilityType: 'সেবার ধরন',
    howLong: 'কতক্ষণ ধরে এই সমস্যা হচ্ছে?',
    extraDetails: 'অতিরিক্ত তথ্য',
    optional: 'ঐচ্ছিক',
    detailsPlaceholder: 'যেমন: সকাল থেকে পানি নেই...',
    submitReport: 'রিপোর্ট জমা দিন',
    submitting: 'জমা হচ্ছে...',
    reportSuccess: 'রিপোর্ট জমা হয়েছে!',
    reportSuccessMsg: 'ধন্যবাদ। আপনার রিপোর্ট প্রতিবেশীদের সাহায্য করবে।',
    signInRequired: 'সাইন ইন প্রয়োজন',
    signInRequiredMsg: 'রিপোর্ট করতে সাইন ইন করুন।',
    signInNow: 'এখনই সাইন ইন করুন',
    fillAllFields: 'সব প্রয়োজনীয় তথ্য পূরণ করুন।',
    signInToReport: 'রিপোর্ট করতে সাইন ইন করুন।',
    noWater: 'পানি নেই',
    lowPressure: 'কম চাপ',
    discoloured: 'রঙিন পানি',
    badSmell: 'দুর্গন্ধ',
    noPower: 'বিদ্যুৎ নেই',
    lowVoltage: 'লো ভোল্টেজ',
    frequentCuts: 'ঘন ঘন লোডশেডিং',
    noGas: 'গ্যাস নেই',
    lowGasPressure: 'গ্যাসের চাপ কম',
    under1hr: '১ ঘণ্টার কম',
    oneToThreeHrs: '১ থেকে ৩ ঘণ্টা',
    over3hrs: '৩ ঘণ্টার বেশি',
    meToo: 'আমারও',
    signInToConfirm: 'নিশ্চিত করতে সাইন ইন করুন।',
    normalSupply: 'স্বাভাবিক সরবরাহ',
    someIssues: 'কিছু সমস্যা রিপোর্ট হয়েছে',
    outageConfirmed: 'বিভ্রাট নিশ্চিত',
    reportsIn2hrs: 'গত ২ ঘণ্টায় রিপোর্ট',
    water: 'পানি',
    electricity: 'বিদ্যুৎ',
    gas: 'গ্যাস',
    allUtilities: 'সব সেবা',
    stats: 'পরিসংখ্যান',
    history: 'জোন ইতিহাস',
  }
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  const toggleLang = () => setLang(l => l === 'en' ? 'bn' : 'en')
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)